-- MySQL Script generated by MySQL Workbench
-- 07/01/16 17:33:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tutorial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tutorial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tutorial` DEFAULT CHARACTER SET utf8 ;
USE `tutorial` ;

-- -----------------------------------------------------
-- Table `tutorial`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`professor` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorial`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`disciplina` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `professor_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_disciplina_professor1_idx` (`professor_codigo` ASC),
  CONSTRAINT `fk_disciplina_professor1`
    FOREIGN KEY (`professor_codigo`)
    REFERENCES `tutorial`.`professor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorial`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`aluno` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorial`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`matricula` (
  `aluno_codigo` INT NOT NULL,
  `disciplina_codigo` INT NOT NULL,
  `semestre` INT NOT NULL,
  `ano` INT NOT NULL,
  PRIMARY KEY (`aluno_codigo`, `disciplina_codigo`, `semestre`, `ano`),
  INDEX `fk_aluno_has_disciplina_disciplina1_idx` (`disciplina_codigo` ASC),
  INDEX `fk_aluno_has_disciplina_aluno_idx` (`aluno_codigo` ASC),
  CONSTRAINT `fk_aluno_has_disciplina_aluno`
    FOREIGN KEY (`aluno_codigo`)
    REFERENCES `tutorial`.`aluno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_codigo`)
    REFERENCES `tutorial`.`disciplina` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
